language: cpp
compiler: gcc

# whitelist
branches:
 - master
 
before_script: 
 - sudo apt-get install -qq libboost-all-dev build-essential gcc g++-4.9 libmysql++-dev libbz2-dev libgmp3-dev
 - cd ghost/src/bncsutil/src/bncsutil 
 - make 
 - sudo make install 
 - cd ../../../StormLib/stormlib 
 - make 
 - sudo make install 
 - cd ../../
 
# Change this to your needs
script: 
 - make
