os: 
  - Windows Server 2012

configuration:
  - Debug
  - Release
  
branches:
  only:
    - master

clone_folder: c:\ohsystem

install:
  - cmd: cd c:\
  - cmd: appveyor DownloadFile http://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.zip
  - cmd: 7z.exe x boost_1_54_0.zip >nul
  - cmd: cd boost_1_54_0
  - cmd: .\bjam
  - cmd: .\b2
  
  
build:
  project: c:\ohsystem\ghost++\ghost.sln
 
 
build_script:
  - cmd: call "%VS120COMNTOOLS%vsvars32.bat"
  - cmd: set INCLUDE=c:\boost_1_54_0;%INCLUDE%
  - cmd: set LibraryPath=c:\boost_1_54_0\stage\lib;$(LibraryPath)
