os: 
  - Windows Server 2012

configuration:
  - Debug
  - Release
  
branches:
  only:
    - master

clone_folder: c:\ohsystem

install:
  - cmd: cd c:\
  - cmd: appveyor DownloadFile http://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.zip
  - cmd: 7z.exe x boost_1_54_0.zip >nul
  - cmd: cd boost_1_54_0
  - cmd: .\bjam
  - cmd: .\b2
  
  
build:
  project: c:\ohsystem\ghost++\ghost.sln
 
 
build_script:
  - cmd: call "%VS120COMNTOOLS%vsvars32.bat"
  - cmd: set INCLUDE=c:\boost_1_54_0;%INCLUDE%
  - cmd: set INCLUDE=c:\boost_1_54_0;%INCLUDE%
  

before_script: 
 - sudo apt-get install -qq libboost-dev build-essential g++ libmysql++-dev wget unzip libbz2-dev libgmp3-dev
 - sudo wget http://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.tar.bz2
 - sudo tar xjf boost_1_54_0.tar.bz2
 - cd boost_1_54_0
 - sudo ./bootstrap.sh --with-libraries=filesystem,program_options,system,regex,thread,date_time --libdir=/usr/lib/
 - sudo ./bjam
 - sudo ./bjam install
 - cd ../
 - cd ghost++/bncsutil/src/bncsutil 
 - make 
 - sudo make install 
 - cd ../../../StormLib/stormlib 
 - make 
 - sudo make install 
 - cd ../../ghost 
 
# Change this to your needs
script: 
 - make
